### ISSUE TITLE
安装此插件后，并没有给图片加上水印

### ISSUE THREAD

**Issue by John-Chan** [SpiritLingPub/hexo-images-watermark#14]
## 环境
OS: Windows 10

`package.json`
```json
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-cli": "^2.0.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-images-watermark": "^2.1.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^6.0.1"
  }
```

`_config.yml`
```yaml
watermark:
    enable: true
    textEnable: true
    rotate: -45
    gravity: centre
    text: cj
```

文章
![TIM图片20200722105016](https://user-images.githubusercontent.com/2360910/88128838-54efe000-cc09-11ea-96fb-ab184d4eaed7.png)

本地运行`hexo server`渲染结果
![TIM图片20200722105102](https://user-images.githubusercontent.com/2360910/88128843-57523a00-cc09-11ea-834e-ae4768ef9cc0.png)

**Comment by SpiritLing** [comment]
## 检查有没有相应输出的

在运行 `hexo s` 后

```
INFO  Start processing    
INFO  Generated Image Process: posts/4cb12659/window-import-mkcert-ca.png
INFO  Generated Image Success: posts/4cb12659/window-import-mkcert-ca.png
INFO  Hexo is running at http://localhost:9999 . Press Ctrl+C to stop.
```

![2020-07-22_17-48-49](https://user-images.githubusercontent.com/26963582/88162278-b9c82c00-cc43-11ea-891d-8a1517a87b30.gif)

输出的蓝色和绿色紫色比较亮一点的，都是有log输出的，看看有没有这张图片

## 比较下面图片

然后看下这个图片下方的那张图片有没有渲染上

下面的有的话，就是引用图片方式导致的问题。

> 如果下面也有问题，那么就发下public下的目录树结构，我再给你看看

**Comment by John-Chan** [comment]
```shell
λ hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
```

没有输出`Generated Image`字样的日志，感觉插件没有生效，我的操作过程是：
- 通过npm安装了`hexo-images-watermark`
- 在 hexo 根目录的`_config.yml`加了那段配置

是不是漏过了什么步骤？

**Comment by SpiritLing** [comment]
你把public目录树给我发下，可以复制出去，发一部分，最好包含你这个文章

**Comment by John-Chan** [comment]
执行`hexo s`只产生一个空的public目录，但是能在浏览器中打开网页，执行`hexo g`后，public目录中目录部分内容如下

`tree  public\ /f > tree.txt`
```shell
F:\_REPO\PRIV\NOTE-ETA\PUBLIC
│  baidusitemap.xml
│  content.json
│  index.html
│  sitemap.xml
│                  
├─2020
│  │              
│  ├─04
│  │  ├─04
│  │  │  └─nacos-server-docker
│  │  │          index.html
│  │  │          nacos-1.2-main.jpg
│  │  │          nacos-1.2-permission.jpg
│  │  │          
│  │  └─27
│  │      └─frp-k8s-inside
│  │              index.html
│  │              K8S-frp.jpg
│  │              
│  │              
│  └─07
│      └─21
│          ├─frp-windows-service
│          │      frp-dir.png
│          │      index.html
│          │      service-mgr.png
│          │      svc-install.png
│          │      wrapper-dir.png
│          │      
│          └─k3s-network-fail
│                  index.html
│                  
```
我截图的测试那个文章是`frp-k8s-inside`

**Comment by SpiritLing** [comment]
看来目录树，我知道你的问题出哪里了
https://github.com/SpiritLingPub/hexo-images-watermark/blob/master/src/main.js#L37
这行代码，插件只获取 `public/posts` 下的图片，也就是文章图片，而你的文章是直接年月日的形式，
当初是为了防止把头像什么的也渲染上，所以就弄了一个这个限制
等我到时候修改下，这是个bug

**Comment by John-Chan** [comment]
感觉这个目录的内容跟主题有关，我使用的主题是[hexo-theme-archer](https://github.com/fi3ework/hexo-theme-archer),是不是可以考虑开放一个配置项，让使用者自己决定排除哪些文件、文件夹。

**Comment by SpiritLing** [comment]
对，所以准备加个配置项，数组形式自定义渲染的文件夹

**Comment by SpiritLing** [comment]
@John-Chan  你先本地安装试试，使用dev分支，用 git+https 方式先安装上，如果没有问题，我就合并发布了

**Comment by John-Chan** [comment]
非常感谢，可以用了。
